spring:
  application:
    name: anden

  datasource:
    url: "jdbc:mysql://localhost:3306/bd_anden?createDatabaseIfNotExist=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
    fetch-registry: true
